#!/bin/bash
# Vercel Deployment Script

echo "🚀 GW2 Achievement Tracker - Vercel Deployment"
echo "================================================"
echo ""
echo "GitHub Repository: https://github.com/efeumutaslan/gw2-achievement-tracker"
echo ""
echo "📋 Deployment Steps:"
echo ""
echo "1️⃣  Vercel CLI Install (if not installed):"
echo "   npm install -g vercel"
echo ""
echo "2️⃣  Login to Vercel:"
echo "   vercel login"
echo "   (Bu komut browser açacak, GitHub ile login ol)"
echo ""
echo "3️⃣  Deploy to Production:"
echo "   vercel --prod"
echo ""
echo "   ✅ Project name: gw2-achievement-tracker"
echo "   ✅ Framework: Vite (auto-detected)"
echo "   ✅ Build Command: npm run build"
echo "   ✅ Output Directory: dist"
echo ""
echo "4️⃣  Deployment tamamlandığında URL alacaksın:"
echo "   🌐 https://gw2-achievement-tracker.vercel.app"
echo ""
echo "================================================"
echo ""
echo "🔗 VEYA Web Dashboard kullan:"
echo ""
echo "1. https://vercel.com adresine git"
echo "2. 'Sign up with GitHub' ile login ol"
echo "3. 'Add New' > 'Project'"
echo "4. 'efeumutaslan/gw2-achievement-tracker' repo'sunu seç"
echo "5. 'Deploy' butonuna tıkla"
echo "6. 2-3 dakika bekle"
echo ""
echo "================================================"
echo ""
echo "✅ Proje Durumu:"
echo "   - Git: Committed & Pushed ✓"
echo "   - TypeScript: Hatalar düzeltildi ✓"
echo "   - Tailwind CSS: v3.4.1 ✓"
echo "   - Vercel Config: vercel.json ✓"
echo "   - Node.js: .nvmrc (20) ✓"
echo ""
echo "🎯 Deployment başarılı olacak!"
echo ""
